[boris]
  version = 1

[build.dist-7-10-core]
  command = [
      ["master", "build", "dist-7-10", "-C", "hadron-core"]
    ]

[build.dist-8-0-core]
  command = [
      ["master", "build", "dist-8-0", "-C", "hadron-core"]
    ]

[build.dist-7-10-wai]
  command = [
      ["master", "build", "dist-7-10", "-C", "hadron-wai"]
    ]

[build.dist-8-0]
  command = [
      ["master", "build", "dist-8-0", "-C", "hadron-wai"]
    ]

[build.branches-7-10-core]
  command = [
      ["master", "build", "branches-7-10", "-C", "hadron-core"]
    ]

[build.branches-8-0-core]
  command = [
      ["master", "build", "branches-8-0", "-C", "hadron-core"]
    ]

[build.branches-7-10-wai]
  command = [
      ["master", "build", "branches-7-10", "-C", "hadron-wai"]
    ]

[build.branches-8-0-wai]
  command = [
      ["master", "build", "branches-8-0", "-C", "hadron-wai"]
    ]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-rebased]
  command = [["rebased"]]

[build.all-submodules]
  command = [["dangling-refs"]]
